### ISSUE TITLE
Right clicking on interact-able with "undiscovered glyph" in hand will prioritize glyph discovery

### ISSUE THREAD

**Issue by MattHartshorn** [Migsect/Inscription#73]
**Description:**
While attempting to use an interact-able object (door, chest, crafting table, etc.) if the player has an *undiscovered glyph* in hand, the glyph will become "discovered". This incorrectly takes priority over the players intended action.

**Expected Behavior:**
The interact-able object should instead be prioritized. For example, the door or chest should be opened.

**Comment by Migsect** [comment]
Merged in with https://github.com/Migsect/Inscription/commit/5e73018780ac9527e96aaa8f29719cc072b59ded
